### ISSUE TITLE
calificacion

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/practica-de-visual-studio-IMA-G#2]
trabajo de los compañeros: 

[INTERFAZ IMANOL.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-IMA-G/files/6191029/INTERFAZ.IMANOL.1.pdf)

cal: 16
falto mas imagenes y mas lineas de conclusión

**Comment by josealfredo79** [comment]
Este trabajo le falta mucho, debe mejorarlo por favor

**Comment by josealfredo79** [comment]
Hay que mejorar el trabajo..revisado.
